name: esdglider
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel #for running things in GCP Jupyter notebooks
  - notebook #For exporting notebooks as html
  - google-crc32c
  - google-cloud-secret-manager

  - SQLAlchemy
  - pyodbc
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - pyyaml

  - GliderTools
  - cmocean

  - pip:
    - dbdreader
    - git+https://github.com/c-proof/pyglider.git@main
    - basemap
    - basemap-data
    - basemap-data-hires

  # conda deactivate && conda env update -f glider-utils/environment.yml --prune
  # After creating and activating conda env,
  # run the following to install esdglider as editable:
  # `pip install -e ~/glider-utils`
