name: esdglider
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel #for running things in GCP Jupyter notebooks
  - notebook #For exporting notebooks as html
  - google-crc32c
  - google-cloud-secret-manager
  - google-cloud-storage

  - SQLAlchemy
  - pyodbc
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - pyyaml

  - GliderTools
  - cmocean
  - cartopy
  - folium

  - pip:
    - dbdreader
    - git+https://github.com/c-proof/pyglider.git@main

# conda env create -f glider-utils/environment.yml
# conda deactivate && conda env update -f glider-utils/environment.yml --prune
# Within active conda env, run to install esdglider as editable:
# pip install -e glider-utils
