name: esdglider
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel #for running things in GCP Jupyter notebooks
  - notebook #For exporting notebooks as html
  - google-crc32c
  - google-cloud-secret-manager
  - google-cloud-storage

  - SQLAlchemy
  - pyodbc
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - pyyaml

  - GliderTools
  - cmocean
  - cartopy
  - folium
  - skyfield
  - timezonefinder

  - pip:
    - dbdreader
    - gspread #conda-forge version is not the latest
    - git+https://github.com/smwoodman/pyglider.git@main
    # - git+https://github.com/c-proof/pyglider.git@main

# conda env create -f esdglider/environment.yml
# conda deactivate && conda env update -f esdglider/environment.yml --prune
# Within active conda env, run to install esdglider as editable:
#   conda activate esdglider && pip install -e esdglider
# Within active conda env, run the following to for install
#   pip install --force-reinstall --no-deps git+https://github.com/smwoodman/pyglider.git@main
