# Compare old and new processed glider deployment files. 
# 
# Code generated by Gemini, and reviewed by Sam Woodman
 
import os
from pathlib import Path
import numpy as np
import pandas as pd
import xarray as xr

# /home/user/miniconda3/envs/esdglider/bin/python /home/user/nc-check.py

# ==============================================================================
# CONFIGURATION - Paths and Tolerance Settings
# ==============================================================================
deployment_name = "calanus-20241019"
OLD_BASE_DIR = (
    Path("/home/user/mnt-gcs/amlr-gliders-deployments-dev")
    / "ECOSWIM" 
    / "2024" / deployment_name
)
NEW_BASE_DIR = (
    # Path("/home/user/mnt-gcs/swfscesd-glider-deployments-data-out")
    Path(f"/home/user/tests/{deployment_name}")
    / "2024" / deployment_name
)

# List of dataset keys/identifiers to evaluate
DATASETS = [
    f"{deployment_name}-delayed-raw.nc",
    f"{deployment_name}-delayed-eng.nc",
    f"{deployment_name}-delayed-sci.nc",
    f"{deployment_name}_grid-delayed-1m.nc",
    f"{deployment_name}_grid-delayed-5m.nc",
    f"{deployment_name}-delayed-profiles.csv", 
]

# Print non-unioned timestamps if the time dimension differs
PRINT_TIME_DIFFS = True
MAX_TIME_DIFFS_TO_PRINT = 10  # Set to None to print all without truncation

# Global attributes to ignore during comparison
EXCLUDE_GLOBAL_ATTRS = {"date_created", "history", "date_issued"}

# Comparison thresholds
ATOL = 1e-5  # Absolute tolerance
RTOL = 1e-5  # Relative tolerance
CHECK_ATTRIBUTES = True  # Compare global and variable metadata
# ==============================================================================


# ==============================================================================
# PATH RESOLUTION LOGIC
# Customize these functions to handle differing directory structures.
# ==============================================================================
def get_old_path(dataset_id: str) -> Path:
    """Returns absolute path to OLD file given a dataset identifier."""
    return OLD_BASE_DIR / "data" / "processed-L1" / dataset_id


def get_new_path(dataset_id: str) -> Path | None:
    """Returns absolute path to NEW file given a dataset identifier."""
    if "raw" in dataset_id or ".csv" in dataset_id:
        path_out = NEW_BASE_DIR / "processed-L0" / dataset_id
    elif "eng" in dataset_id or "sci" in dataset_id:
        path_out = NEW_BASE_DIR / "processed-L1" / dataset_id
    elif "grid" in dataset_id:
        path_out = NEW_BASE_DIR / "processed-L3" / dataset_id
    else:
        print("dataset_id syntax not recognized")
        path_out = None

    return path_out


# ==============================================================================


def compare_xarray_datasets(
    ds_old: xr.Dataset,
    ds_new: xr.Dataset,
    atol: float,
    rtol: float,
    check_attrs: bool,
    exclude_global_attrs: set[str] | None = None,
    print_time_diffs: bool = False,
    max_time_diffs: int | None = 10,
) -> tuple[list[str], list[str], list[str]]:
    """Compares two xarray datasets and returns (meta_diffs, struct_diffs, value_diffs)."""
    meta_diffs = []
    struct_diffs = []
    value_diffs = []

    if exclude_global_attrs is None:
        exclude_global_attrs = set()

    # 1. Check Dimensions (Structural)
    if dict(ds_old.sizes) != dict(ds_new.sizes):
        struct_diffs.append(
            f"Dimension mismatch:\n    OLD: {dict(ds_old.sizes)}\n    NEW: {dict(ds_new.sizes)}"
        )

    # 2. Check Time Coordinates
    if "time" in ds_old.coords and "time" in ds_new.coords:
        time_old = pd.Index(ds_old["time"].values)
        time_new = pd.Index(ds_new["time"].values)

        if not time_old.equals(time_new):
            only_in_old = time_old.difference(time_new)
            only_in_new = time_new.difference(time_old)

            time_msg = [
                f"Time coordinate values differ (OLD count: {len(time_old)}, NEW count: {len(time_new)})"
            ]

            if print_time_diffs:
                if len(only_in_old) > 0:
                    time_msg.append(
                        f"    - Timestamps only in OLD ({len(only_in_old)} total):"
                    )
                    limit = (
                        len(only_in_old)
                        if max_time_diffs is None
                        else min(max_time_diffs, len(only_in_old))
                    )
                    for t in only_in_old[:limit]:
                        time_msg.append(f"        {t}")
                    if max_time_diffs and len(only_in_old) > max_time_diffs:
                        time_msg.append(
                            f"        ... (+{len(only_in_old) - max_time_diffs} more)"
                        )

                if len(only_in_new) > 0:
                    time_msg.append(
                        f"    - Timestamps only in NEW ({len(only_in_new)} total):"
                    )
                    limit = (
                        len(only_in_new)
                        if max_time_diffs is None
                        else min(max_time_diffs, len(only_in_new))
                    )
                    for t in only_in_new[:limit]:
                        time_msg.append(f"        {t}")
                    if max_time_diffs and len(only_in_new) > max_time_diffs:
                        time_msg.append(
                            f"        ... (+{len(only_in_new) - max_time_diffs} more)"
                        )

            value_diffs.append("\n".join(time_msg))
    elif ("time" in ds_old.coords) != ("time" in ds_new.coords):
        struct_diffs.append(
            f"Time coordinate presence mismatch (OLD: {'time' in ds_old.coords}, NEW: {'time' in ds_new.coords})"
        )

    # 3. Check Global Attributes (Metadata)
    if check_attrs:
        old_attrs = {
            str(k): v
            for k, v in ds_old.attrs.items()
            if str(k) not in exclude_global_attrs
        }
        new_attrs = {
            str(k): v
            for k, v in ds_new.attrs.items()
            if str(k) not in exclude_global_attrs
        }

        if old_attrs != new_attrs:
            diff_keys = (set(old_attrs.keys()) ^ set(new_attrs.keys())).union(
                k
                for k in old_attrs.keys() & new_attrs.keys()
                if old_attrs[k] != new_attrs[k]
            )

            details = []
            for k in sorted(diff_keys):
                v_old = old_attrs.get(k, "<MISSING>")
                v_new = new_attrs.get(k, "<MISSING>")
                details.append(f"      - {k}: OLD={v_old} | NEW={v_new}")

            meta_diffs.append("Global attributes differ:\n" + "\n".join(details))

    # 4. Check Variables Availability (Structural)
    old_vars: set[str] = {str(v) for v in ds_old.data_vars}
    new_vars: set[str] = {str(v) for v in ds_new.data_vars}

    missing_in_new = old_vars - new_vars
    missing_in_old = new_vars - old_vars

    if missing_in_new:
        struct_diffs.append(
            f"Variables present in OLD but missing in NEW: {sorted(missing_in_new)}"
        )
    if missing_in_old:
        struct_diffs.append(
            f"Variables present in NEW but missing in OLD: {sorted(missing_in_old)}"
        )

    # 5. Check Variable Shapes (Structural), Attributes (Metadata), & Values (Data Values)
    common_vars = sorted(old_vars & new_vars)

    for var in common_vars:
        da_old = ds_old[var]
        da_new = ds_new[var]

        # Variable-level attributes (Metadata)
        if check_attrs and da_old.attrs != da_new.attrs:
            meta_diffs.append(f"Variable '{var}' attributes differ.")

        # Variable Shape (Structural)
        if da_old.shape != da_new.shape:
            struct_diffs.append(
                f"Variable '{var}' shape mismatch (OLD: {da_old.shape}, NEW: {da_new.shape})"
            )
            continue

        val_old = da_old.values
        val_new = da_new.values

        # Skip value checks for non-numeric arrays
        if not np.issubdtype(val_old.dtype, np.number):
            if not np.array_equal(val_old, val_new):
                value_diffs.append(
                    f"Non-numeric variable '{var}' contents do not match."
                )
            continue

        # Check NaN placements (Data Value)
        nan_mask_old = np.isnan(val_old)
        nan_mask_new = np.isnan(val_new)

        if not np.array_equal(nan_mask_old, nan_mask_new):
            value_diffs.append(
                f"Variable '{var}' NaN/FillValue locations do not match."
            )

        # Numerical comparison on valid numbers (Data Value)
        valid_mask = ~nan_mask_old & ~nan_mask_new
        if np.any(valid_mask):
            v_old = val_old[valid_mask]
            v_new = val_new[valid_mask]

            is_close = np.isclose(
                v_old, v_new, rtol=rtol, atol=atol, equal_nan=True
            )

            if not np.all(is_close):
                abs_diff = np.abs(v_old - v_new)
                max_diff = np.max(abs_diff)
                mean_diff = np.mean(abs_diff)
                diff_count = np.sum(~is_close)
                pct_diff = (diff_count / len(v_old)) * 100

                value_diffs.append(
                    f"Variable '{var}' numeric values exceed tolerance:\n"
                    f"    - Mismatched points: {diff_count}/{len(v_old)} ({pct_diff:.2f}%)\n"
                    f"    - Max Abs Difference:  {max_diff:.6e}\n"
                    f"    - Mean Abs Difference: {mean_diff:.6e}"
                )

    return meta_diffs, struct_diffs, value_diffs


def compare_csv_files(
    old_path: Path,
    new_path: Path,
    atol: float,
    rtol: float,
) -> tuple[list[str], list[str], list[str]]:
    """Compares two CSV files and returns (meta_diffs, struct_diffs, value_diffs)."""
    meta_diffs = []
    struct_diffs = []
    value_diffs = []

    df_old = pd.read_csv(old_path)
    df_new = pd.read_csv(new_path)

    # 1. Check Shape (Structural)
    if df_old.shape != df_new.shape:
        struct_diffs.append(
            f"CSV Shape mismatch (Rows, Cols): OLD {df_old.shape} vs NEW {df_new.shape}"
        )

    # 2. Check Column Names (Structural)
    old_cols = set(df_old.columns)
    new_cols = set(df_new.columns)

    if old_cols != new_cols:
        missing_in_new = old_cols - new_cols
        missing_in_old = new_cols - old_cols
        if missing_in_new:
            struct_diffs.append(
                f"Columns present in OLD but missing in NEW: {sorted(missing_in_new)}"
            )
        if missing_in_old:
            struct_diffs.append(
                f"Columns present in NEW but missing in OLD: {sorted(missing_in_old)}"
            )

    # 3. Cell-by-Cell Comparison across Shared Columns (Data Values)
    common_cols = [c for c in df_old.columns if c in new_cols]

    if len(df_old) == len(df_new):
        for col in common_cols:
            s_old = df_old[col]
            s_new = df_new[col]

            # Null / NaN positioning check
            nan_mask_old = s_old.isna()
            nan_mask_new = s_new.isna()

            if not (nan_mask_old == nan_mask_new).all():
                value_diffs.append(
                    f"Column '{col}' Null/NaN locations do not match."
                )

            # Numeric comparison
            if pd.api.types.is_numeric_dtype(
                s_old
            ) and pd.api.types.is_numeric_dtype(s_new):
                valid_mask = ~nan_mask_old & ~nan_mask_new
                if valid_mask.any():
                    v_old = s_old[valid_mask].to_numpy()
                    v_new = s_new[valid_mask].to_numpy()

                    is_close = np.isclose(
                        v_old, v_new, rtol=rtol, atol=atol, equal_nan=True
                    )

                    if not is_close.all():
                        abs_diff = np.abs(v_old - v_new)
                        max_diff = np.max(abs_diff)
                        diff_count = np.sum(~is_close)
                        pct_diff = (diff_count / len(v_old)) * 100

                        value_diffs.append(
                            f"Column '{col}' numeric values exceed tolerance:\n"
                            f"    - Mismatched rows: {diff_count}/{len(v_old)} ({pct_diff:.2f}%)\n"
                            f"    - Max Abs Difference: {max_diff:.6e}"
                        )
            else:
                # String / Object comparison
                if not s_old.equals(s_new):
                    mismatches = (s_old != s_new) & (
                        ~nan_mask_old | ~nan_mask_new
                    )
                    diff_count = mismatches.sum()
                    value_diffs.append(
                        f"Non-numeric column '{col}' content differs across {diff_count} rows."
                    )

    return meta_diffs, struct_diffs, value_diffs


def process_dataset(dataset_id: str) -> str:
    """Identifies file extension, opens files with the appropriate library, and compares them."""
    old_file = get_old_path(dataset_id)
    new_file = get_new_path(dataset_id)

    if new_file is None:
        return "MISSING"

    if not old_file.exists():
        print(f"ERROR: Old path does not exist: {old_file}")
        return "MISSING"

    if not new_file.exists():
        print(f"ERROR: New path does not exist: {new_file}")
        return "MISSING"

    print(f"  OLD: {old_file}")
    print(f"  NEW: {new_file}")

    file_ext = old_file.suffix.lower()

    if file_ext == ".nc":
        print("Analyzing NetCDF datasets with xarray...")
        with (
            xr.open_dataset(old_file) as ds_old,
            xr.open_dataset(new_file) as ds_new,
        ):
            meta_diffs, struct_diffs, value_diffs = compare_xarray_datasets(
                ds_old,
                ds_new,
                atol=ATOL,
                rtol=RTOL,
                check_attrs=CHECK_ATTRIBUTES,
                exclude_global_attrs=EXCLUDE_GLOBAL_ATTRS,
                print_time_diffs=PRINT_TIME_DIFFS,
                max_time_diffs=MAX_TIME_DIFFS_TO_PRINT,
            )
    elif file_ext == ".csv":
        print("Analyzing CSV datasets with pandas...")
        meta_diffs, struct_diffs, value_diffs = compare_csv_files(
            old_file,
            new_file,
            atol=ATOL,
            rtol=RTOL,
        )
    else:
        print(f"ERROR: Unsupported file format '{file_ext}' for {dataset_id}")
        return "MISSING"

    # Evaluate Result Status
    if not meta_diffs and not struct_diffs and not value_diffs:
        print("RESULT: MATCH (Files are completely identical)")
        return "MATCH"

    if meta_diffs:
        print("\n  [Metadata Differences]:")
        for diff in meta_diffs:
            print(f"    • {diff}")

    if struct_diffs:
        print("\n  [Structural Differences]:")
        for diff in struct_diffs:
            print(f"    • {diff}")

    if value_diffs:
        print("\n  [Data Value Differences]:")
        for diff in value_diffs:
            print(f"    • {diff}")

    # Determine Classification Status for Summary Report
    if struct_diffs and value_diffs:
        return "STRUCTURAL_AND_VALUE"
    elif struct_diffs:
        return "STRUCTURAL_ONLY"
    elif value_diffs:
        return "VALUE_ONLY"
    else:
        return "METADATA_ONLY"


def main():
    print(f"Starting analysis on {len(DATASETS)} dataset(s)...")

    summary = {
        "MATCH": [],
        "METADATA_ONLY": [],
        "STRUCTURAL_ONLY": [],
        "VALUE_ONLY": [],
        "STRUCTURAL_AND_VALUE": [],
        "MISSING": [],
    }

    for dataset_id in DATASETS:
        print("\n" + "=" * 60)
        print(f"DATASET: {dataset_id}")
        print("=" * 60)

        status = process_dataset(dataset_id)
        summary[status].append(dataset_id)

    print("\n" + "=" * 60)
    print("FINAL SUMMARY REPORT")
    print("=" * 60)
    print(f"Total Evaluated:          {len(DATASETS)}")
    print(f"Full Matches:             {len(summary['MATCH'])}")
    print(f"Metadata-Only Diffs:      {len(summary['METADATA_ONLY'])}")
    print(f"Structural Diffs Only:    {len(summary['STRUCTURAL_ONLY'])}")
    print(f"Data Value Diffs Only:    {len(summary['VALUE_ONLY'])}")
    print(f"Structural + Value Diffs: {len(summary['STRUCTURAL_AND_VALUE'])}")
    print(f"Missing Files:            {len(summary['MISSING'])}")

    if summary["METADATA_ONLY"]:
        print("\nDatasets with Metadata-Only differences:")
        for d in summary["METADATA_ONLY"]:
            print(f"  - {d}")

    if summary["STRUCTURAL_ONLY"]:
        print("\nDatasets with Structural differences only:")
        for d in summary["STRUCTURAL_ONLY"]:
            print(f"  - {d}")

    if summary["VALUE_ONLY"]:
        print("\nDatasets with Data Value differences only:")
        for d in summary["VALUE_ONLY"]:
            print(f"  - {d}")

    if summary["STRUCTURAL_AND_VALUE"]:
        print("\nDatasets with BOTH Structural and Data Value differences:")
        for d in summary["STRUCTURAL_AND_VALUE"]:
            print(f"  - {d}")

    if summary["MISSING"]:
        print("\nDatasets with missing files:")
        for d in summary["MISSING"]:
            print(f"  - {d}")


if __name__ == "__main__":
    main()
    