"""
Update glider YAML configuration files.

Code generated by Gemini, and reviewed by Sam Woodman
"""

from pathlib import Path

import yaml

# Directory containing your glider YAML config files
CONFIG_DIR = Path("/home/user/glider-processing/deployment-configs/2018")
# CONFIG_DIR = Path("/home/user/tests/amlr08-20220513")
# CONFIG_DIR = Path("/home/user/tests/calanus-20241019")

# Map top-level sections -> variable names -> desired attrs
NEW_BOUNDS = {
    "netcdf_variables": {
        "chlorophyll": {"valid_min": 0.0, "valid_max": 50.0},
        "cdom": {"valid_min": 0.0},
        "backscatter_700": {"valid_min": 0.0, "units": "m-1 sr-1"},
        "oxygen_concentration": {"valid_min": 0.0, "valid_max": 500.0},
        "oxygen_saturation": {"valid_min": 0.0, "valid_max": 120.0},
        "par": {"valid_min": 0.0, "valid_max": 3500.0, "units": "umol m-2 s-1"},
        "temperature": {"units": "degrees_C"},
    },
    "glider_devices": {
        "instrument_glidercam": {"long_name": "Wassoc Glidercam"},
        "instrument_shadowgraph": {"long_name": "Wassoc Shadowgraph Camera"},
        "instrument_azfp": {"long_name": "Acoustic Zooplankton Fish Profiler"},
        "instrument_echosounder": {"long_name": "Nortek Sig 100 Compact Echosounder"},
        "instrument_par": {"long_name": "Photosynthetically Active Radiation (PAR) Sensor"},
        "instrument_dmon": {"long_name": "WHOI Digital Acoustic Monitoring Instrument DMON"},
        "instrument_wispr": {"long_name": "WISPR Passive Acoustic Monitoring System "},
        "instrument_hydrophone": {"long_name": "Hydrophone for WISPR"},
    }
}

NEW_CONFIG = {    
    "profile_variables": {
        "instrument_ctd": {"comment": "placeholder for pyglider profile extraction"},
    },
    "metadata": {
        "disclaimer": (
            "This data may be redistributed and used without restriction.  "
            "Data provided as is with no expressed or implied assurance "
            "of quality assurance or quality control"
        ), 
        "license": (
            "These data were produced by NOAA and are not "
            "subject to copyright protection in the United States. "
            "NOAA waives any potential copyright and related rights in thse data "
            "worldwide through the Creative Commons Zero 1.0 Universal Public "
            "Domain Dedication "
            "(CC0-1.0, https://creativecommons.org/publicdomain/zero/1.0/)."
        )
    },
}


def find_yaml_files(directory_path: Path):
    return [p for p in directory_path.rglob('*') if p.suffix.lower() in ('.yaml', '.yml') and p.is_file()]


def add_profile_variables(data: dict) -> dict:
    """Updates key/value attributes for specific sections and returns data."""
    print("Adding instrument_ctd to profile variables")
    if "profile_variables" in data:
        data["profile_variables"]["instrument_ctd"] = {"comment": "placeholder for pyglider profile extraction"}
    else:
        print("WARNING: 'profile_variables' section not found in data.")
    return data


def add_disclaimer_and_license(data: dict) -> dict:
    """Adds disclaimer and license to metadata, regardless of if present and returns data."""
    print("Adding disclaimer and license to metadata if not already present.")
    if "metadata" not in data or not isinstance(data["metadata"], dict):
        print("WARNING: 'metadata' section not found in data.")
    else:
        data["metadata"]["disclaimer"] = (
            "This data may be redistributed and used without restriction.  "
            "Data provided as is with no expressed or implied assurance "
            "of quality assurance or quality control"
        )
        data["metadata"]["license"] = (
            "These data were produced by NOAA and are not "
            "subject to copyright protection in the United States. "
            "NOAA waives any potential copyright and related rights in thse data "
            "worldwide through the Creative Commons Zero 1.0 Universal Public "
            "Domain Dedication "
            "(CC0-1.0, https://creativecommons.org/publicdomain/zero/1.0/)."
        )

    return data


def update_bounds(data: dict, updates: dict) -> dict:
    """Updates key/value attributes for specific sections and returns data."""
    print("Updating bounds for given sections and variables.")
    for section_name, var_updates in updates.items():
        if section_name in data and isinstance(data[section_name], dict):
            for var_name, bounds in var_updates.items():
                if var_name in data[section_name]:
                    data[section_name][var_name].update(bounds)
    return data


def remove_deployment_id(data: dict) -> dict:
    """Removes 'deployment_id' from metadata if present and returns data."""
    print("Removing 'deployment_id' from metadata if present.")
    if isinstance(data.get('metadata'), dict):
        data['metadata'].pop('deployment_id', None)
    return data


def rename_deployment_min_dt(data: dict) -> dict:
    """Renames 'deployment_min_dt' to 'start_date' in metadata and returns data."""
    print("Renaming 'deployment_min_dt' to 'start_date' in metadata if present.")

    if isinstance(data.get('metadata'), dict) and 'deployment_min_dt' in data['metadata']:
        data['metadata']['start_date'] = data['metadata'].pop('deployment_min_dt')
        
    return data


def update_glider_configs(config_directory: Path, updates: dict):
    yaml_files = find_yaml_files(config_directory)

    for file_path in yaml_files:
        with open(file_path, "r", encoding="utf-8") as f:
            print(f"Processing file: {file_path.name}")
            data = yaml.safe_load(f)

        if not isinstance(data, dict):
            continue

        # Pipeline transformations
        data = add_profile_variables(data)
        data = add_disclaimer_and_license(data)
        data = update_bounds(data, updates)
        data = remove_deployment_id(data)
        data = rename_deployment_min_dt(data)

        
        # Sort the keys within the metadata dictionary alphabetically
        print(f"Sorting keys for metadata and glider_devices for file: {file_path.name}")
        data['metadata'] = dict(sorted(data['metadata'].items()))
        data['glider_devices'] = dict(sorted(data['glider_devices'].items()))

        # Unconditionally rewrite file
        with open(file_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, sort_keys=False, default_flow_style=False)
        print(f"Successfully wrote: {file_path.name}")


if __name__ == "__main__":
    update_glider_configs(CONFIG_DIR, NEW_BOUNDS)
    