"""
Update glider YAML configuration files.

Code generated by Gemini, and reviewed by Sam Woodman
"""

from pathlib import Path
import yaml

# Directory containing your glider YAML config files
CONFIG_DIR = Path("/home/user/glider-lab/deployment-configs")
# CONFIG_DIR = Path("/home/user/tests/amlr08-20220513")

# Map top-level sections -> variable names -> desired attrs
NEW_BOUNDS = {
    "netcdf_variables": {
        "chlorophyll": {"valid_min": 0.0, "valid_max": 50.0},
        "oxygen_concentration": {"valid_min": 0.0, "valid_max": 500.0},
        "par": {"valid_min": 0.0, "valid_max": 2000.0, "units": "umol m-2 s-1"},
        "temperature": {"units": "degrees_C"},
        "backscatter_700": {"units": "m-1 sr-1"},
    },
    # "profile_variables": {
    #     "profile_time": {"valid_min": 0.0, "valid_max": 2000000000.0},
    # },
}

def update_glider_configs(config_directory: Path, updates: dict):
    for file_path in config_directory.glob("*.yml"):
        with open(file_path, "r", encoding="utf-8") as f:
            print(f"Processing file: {file_path.name}")
            data = yaml.safe_load(f)

        file_updated = False

        for section_name, var_updates in updates.items():
            if section_name in data and isinstance(data[section_name], dict):
                for var_name, bounds in var_updates.items():
                    if var_name in data[section_name]:
                        data[section_name][var_name].update(bounds)
                        file_updated = True

        if file_updated:
            with open(file_path, "w", encoding="utf-8") as f:
                # sort_keys=False maintains key ordering
                # default_flow_style=False ensures YAML block style instead of JSON style
                yaml.dump(data, f, sort_keys=False, default_flow_style=False)
            print(f"Successfully updated: {file_path.name}")

if __name__ == "__main__":
    update_glider_configs(CONFIG_DIR, NEW_BOUNDS)
    